deny_domains_extract = [
    'https://support.google.com/',
    'https://www.google.com/',
    'https://accounts.google.com/',
    'https://maps.google.com/',
    'https://www.instagram.com/',
    'https://www42.bb.com.br/',
    'https://www.poupex.com.br/',
    'http://support.google.com/',
    'http://support.google.com/',
    'http://www.google.com/',
    'http://accounts.google.com/',
    'http://maps.google.com/',
    'http://www.instagram.com/',
    'http://www42.bb.com.br/',
    'http://www.poupex.com.br/',
    'https://www.bb.com.br/',
    'https://web.whatsapp.com/',
    'http://www8.caixa.gov.br/',
    'https://b-m.facebook.com/',
    'https://www.waze.com/',
    'https://www.youtube.com/',

]