# Generated by Django 3.1.6 on 2021-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_basiccrawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccrawler',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
