# Generated by Django 3.1.6 on 2021-03-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_blacklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapyImproviment',
            new_name='ScrapyImprovement',
        ),
        migrations.RenameField(
            model_name='scrapyimprovement',
            old_name='original',
            new_name='url',
        ),
    ]
